app/chef/__init__.py
# app/chef/__init__.py

from flask import Blueprint

home = Blueprint('chef', __name__)

from . import views

app/chef/views.py
# app/chef/views.py
from flask import abort, flash, redirect, render_template, url_for
form flask_login import current_user, login_required

from flask import render_template
from flask_login import login_required

from . import chef
from forms import AddRecipesForm, EditRecipesForm, AddCategoryForm, EditCategoryForm
 
from .. import db
from ..models import Recipe, RecipeCategory, User


def check_chef():
    """
    Prevent non-chefs from accessing the page
    """
    if not current_user.is_chef:
        abort(403)

# Recipe views
@chef.route('/recipes', methods=['GET', 'POST'])
@login_required
def list_recipes():
    """
    List all recipes
    """

    check_recipe()

    recipes = Recipe.query.all()

    return render_template('chef/recipes.html',
                           recipes=recipes, title="Recipes")

@chef.route('/recipes', methods=['GET', 'POST'])
@login_required
def add_recipe():
    """
    Add recipes
    """
    check_chef()

    add_recipe = True

    form = RecipeForm()
    if form.validate_on_submit():
        recipe = Recipe(recipe_name=form.recipe_name.data,
                        people_served = form.people_served.data,
                        quantity = form.quantity.data,
                        ingredient = form.ingredient.data,
                        making_steps = form.making_steps.data
                        recipe.category = form.category.data
                        recipe.cook = form.cook.data)
        try:
            #add recipe to the database
            db.session.add(recipe)
            db.session.commit()
            flash('You have successfully added a new recipe.')
        except:
            # in case recipe name already exists
            flash('Error: recipe name already exists.')

        # redirect to recipes page
        return redirect(url_for('chef.list_recipes'))

    # load recipes template
    return render_template('chef/recipes.html', action="Add",
                           add_recipe=add_recipe, form=form,
                           title="Add Recipe")

@chef.route('/recipes/edit/<int:recipe_id>', methods=['GET', 'POST'])
@login_required
def edit_recipe(recipe_id):
    """
    Edit a recipe
    """

    check_chef()

    add_recipe = False

    recipe = Recipe.query.get_or_404(recip_id)
    form = Recipe_on_submit():
        if form.validate_on_submit():
            recipe_name=form.recipe_name.data,
            people_served = form.people_served.data,
            quantity = form.quantity.data,
            ingredient = form.ingredient.data,
            making_steps = form.making_steps.data
            recipe.category = form.category.data
            recipe.cook = form.cook.data)
            db.session.commit()
            flash('You have successfully edited the recipe.')

            # redirect to the recipe
            return redirect(url_for('chef.list_recipes'))

        form.recipe_name.data = recipe.recipe_name
        form.people_served = recipe.people_served
        form.quantity = recipe.quantity
        form.ingredient = recipe.ingredient
        form.making_steps = recipe.making_steps
        form.category = recipe.category
        form.cook = form.cook

        return render_template('chef/recipe.hml', action="Edit",
                               add_recipe=add_recipe, form=form,
                               recipe=recipe, title="Edit Recipe")

@admin.rout('/recipes/delete<int:id2>', methods=['GET', 'POST'])
@login_required
def delete_recipe(id2):
    
    """
    Delete a recipe from the database
    """
    chek_chef()

    recipe = Recipe.query.get_or_404(id2)
    db.session.delete(recipe)
    db.session.commit()
    flash('You have successfully deleted a recipe.')

    # redirect to the recipes page
    return render_template(title="Delete Recipe")
    return redirect(url_for('chef.list_recipes'))
    

# Recipe Category Views
@chef.route('/recipe_categories', methods=['GET', 'POST'])
@login_required
def list_recipe_categories():
    """
    List all recipe categories
    """

    check_recipe_category()

    recipe_categories = RecipeCategory.query.all()

    return render_template('admin/recipe_category.html',
                           recipe_categories=recipe_categories, title="Recipe Categories")

@chef.route('/recipe_categories', methods=['GET', 'POST'])
@login_required
def add_recipe_category():
    """
    Add a recipe category
    """
    check_chef()

    add_recipe_category = True

    form = RecipeCategoryForm()
    if form.validate_on_submit():
        recipe_category = RecipeCategory(category_name=form.recipe_name.data,
                        details = form.details.data)
        try:
            #add recipe to the database
            db.session.add(recipe_category)
            db.session.commit()
            flash('You have successfully added a new recipe category.')
        except:
            # in case recipe category name already exists
            flash('Error: recipe category name already exists.')

        # redirect to recipe categories page
        return redirect(url_for('chef.list_recipe_categories'))

    # load recipe categories template
    return render_template('chef/recipe_categories.html', action="Add",
                           add_recipe_category=add_recipe_category, form=form,
                           title="Add Recipe Category")

@chef.route('/recipes_categories/edit/<int:cat_id>', methods=['GET', 'POST'])
@login_required
def edit_recipe_category(cat_id):
    """
    Edit a recipe category
    """

    check_chef()

    add_recipe_category = False

    recipe_category = RecipeCategory.query.get_or_404(cat_id)
    form = Recipe_on_submit():
        if form.validate_on_submit():
            category_name=form.category_name.data,
            details = form.details.data
            db.session.commit()
            flash('You have successfully edited the recipe category.')

            # redirect to the recipe
            return redirect(url_for('chef.list_recipe_categories'))

        form.category_name.data = recipe_category.category_name
        form.user = form.user

        return render_template('chef/recipe_category.hml', action="Edit",
                               add_recipe_category=add_recipe_category, form=form,
                               recipe_category=recipe_category, title="Edit Recipe Category")

    

@chef.rout('/recipe_categories/delete<int:id2>', methods=['GET', 'POST'])
@login_required
def delete_recipe_category(id2):
    
    """
    Delete a recipe category from the database
    """
    chek_chef()

    recipe_category = RecipeCategory.query.get_or_404(id2)
    db.session.delete(recipe_category)
    db.session.commit()
    flash('You have successfully deleted a recipe category.')

    # redirect to the recipe categories page
    return render_template(title="Delete Recipe Category")
    return redirect(url_for('chef.list_recipe_categores'))
    

            

app/recipes/__init__.py
# app/recipes/__init__.py

from flask import Blueprint

recipes = Blueprint('recipes', __name__)

from . import views

app/recipes/views.py
#app/recipe/views.py

from flask import render_template
from flask_login import login_required

from . import recipe

# Recipe views
@recipes.route('/recipes', methods=['GET', 'POST'])

def list_recipes():
    """
    List all recipes
    """

    check_recipe()

    recipes = Recipe.query.all()

    return render_template('chef/recipes.html',
                           recipes=recipes, title="Recipes")


                        

app/templates/chef/recipe.html
!-- app/templates/chef/recipe.html -->

{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_recipe %}
        Add Recipe
    {% else %}
        Edit Recipe
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_recipe %}
                <h1>Add Recipe</h1>
            {% else %}
                <h1>Edit Recipe</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/chef/recipe_categories.html
<!-- app/templates/chef/recipe_categories.html -->

{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Recipes Categories{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Recipe Categories</h1>
        {% if recipes %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="15%"> Name </th>
                   <th width="40%"> Details </th>
                  

                  <th width="15%"> Edit </th>
                  <th width="15%"> Delete </th>
                </tr>
              </thead>
              <tbody>
              {% for category in recipe_categories %}
                <tr>
                  <td> {{ recipe.category_name }} </td>
                  <td> {{ recipe.details }} </td>
                  

                 
                  <td>
                    <a href="{{ url_for('chef.edit_recipe_category', id=category.category_id) }}">
                      <i class="fa fa-pencil"></i> Edit 
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('chef.delete_recipe_category', id=category.category_id) }}">
                      <i class="fa fa-trash"></i> Delete 
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No recipe categories have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('chef.add_recipe_category') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Recipe Category
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/chef/recipe_category.html
!-- app/templates/chef/recipe_category.html -->

{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_recipe_category %}
        Add Recipe Category
    {% else %}
        Edit Recipe Category
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_recipe_category %}
                <h1>Add Recipe Category</h1>
            {% else %}
                <h1>Edit Recipe Category</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/chef/recipes.html
<!-- app/templates/chef/recipes.html -->

{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Recipes{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Recipes</h1>
        {% if recipes %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="15%"> Name </th>
                  <th width="15%"> Plates </th>
                  <th width="15%"> Quantity </th>
                   <th width="40%"> Ingredient </th>
                    <th width="40%"> Steps  </th>

                  <th width="15%"> Edit </th>
                  <th width="15%"> Delete </th>
                </tr>
              </thead>
              <tbody>
              {% for recipe in recipes %}
                <tr>
                  <td> {{ recipe.recipe_name }} </td>
                  <td> {{ recipe.people_served }} </td>
                  <td> {{ reciepe.quantity }} </td>
                  <td> {{ recipe.ingredient }} </td>
                  <td> {{ recipe.making_steps }} </td>

                 
                  <td>
                    <a href="{{ url_for('chef.edit_recipe', id=recipe.recipe_id) }}">
                      <i class="fa fa-pencil"></i> Edit 
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('chef.delete_recipe', id=recipe.recipe_id) }}">
                      <i class="fa fa-trash"></i> Delete 
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No recipes have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('chef.add_recipe') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Recipe
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}